"""initial_schema

Revision ID: 0148a4e8a170
Revises: 
Create Date: 2026-06-06 12:07:30.542579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0148a4e8a170'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('tenant_slug', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_candidates_tenant_slug'), 'candidates', ['tenant_slug'], unique=False)
    op.add_column('transactions', sa.Column('tenant_slug', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_transactions_tenant_slug'), 'transactions', ['tenant_slug'], unique=False)
    op.add_column('votes', sa.Column('tenant_slug', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_votes_candidate_id'), 'votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_votes_tenant_slug'), 'votes', ['tenant_slug'], unique=False)
    op.create_index('ix_votes_user_candidate_season_tenant', 'votes', ['user_id', 'candidate_id', 'season_year', 'tenant_slug'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index('ix_votes_user_candidate_season_tenant', table_name='votes')
    op.drop_index(op.f('ix_votes_tenant_slug'), table_name='votes')
    op.drop_index(op.f('ix_votes_candidate_id'), table_name='votes')
    op.drop_column('votes', 'tenant_slug')
    op.drop_index(op.f('ix_transactions_tenant_slug'), table_name='transactions')
    op.drop_column('transactions', 'tenant_slug')
    op.drop_index(op.f('ix_candidates_tenant_slug'), table_name='candidates')
    op.drop_column('candidates', 'tenant_slug')
    # ### end Alembic commands ###
